# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20180228_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_libreta',
            field=models.IntegerField(unique=True),
        ),
    ]
