# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 17:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20180301_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ciudad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_libreta',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='observaciones',
            field=models.CharField(default='', max_length=200),
        ),
    ]
